### ISSUE TITLE
The node that represents me is not in the middle of the graph

### ISSUE THREAD

**Issue by Fabulani** [EliotAndres/facebook-friend-graph#2]
I've generated the graph with 58 friends (-9) and it clustered together two groups of people. That part is fine. The thing is, the node that represents me is in the corner of the graph, without any edges attached to it. See image [here](https://drive.google.com/open?id=1VSnubJ9V4_LzZ4um1pr-1pqYSEPfemWY).

Pickle file can be found [here](https://drive.google.com/open?id=1c3AZ5xumz88ptoqMlqOKiuXlqIa-JTw7).

*Note: my facebook username is **fabiano.manschein**, just in case that's necessary.

**Comment by Fabulani** [comment]
Fixed this issue by changing the following line in the last for loop of the third input of the notebook:

`if item in central_friends.keys() `
changed to
`if item in central_friends.keys() or item == CENTRAL_ID:`

**Comment by EliotAndres** [comment]
@Fabulani Thank you for this other fix. I added it to the master branch.
