### ISSUE TITLE
Not detecting all friends (only 60 out of 250 are found)

### ISSUE THREAD

**Issue by Fabulani** [EliotAndres/facebook-friend-graph#3]
Title says it all. The program isn't being able to detect all friends due to the scrolling down problem.

**Comment by Fabulani** [comment]
This issue was resolved by making changes to the `def get_fb_page(url)` section of the `facebookFOF.py` code according to this post: [link here](https://stackoverflow.com/questions/20986631/how-can-i-scroll-a-web-page-using-selenium-webdriver-in-python)

The function definition ends up like this:


```
    def get_fb_page(url):
        time.sleep(2)
        driver.get(url)
        SCROLL_PAUSE_TIME = 2
    
        # Get scroll height
        last_height = driver.execute_script("return document.body.scrollHeight")
    
        while True:
            # Scroll down to bottom
            driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
    
            # Wait to load page
            time.sleep(SCROLL_PAUSE_TIME)
    
            # Calculate new scroll height and compare with last scroll height
            new_height = driver.execute_script("return document.body.scrollHeight")
            if new_height == last_height:
                break
            last_height = new_height
        html_source = driver.page_source
        return html_source

```

`SCROLL_PAUSE_TIME` defines how much time the program waits for the page to load before attempting another scroll. 2 seconds seemed pretty good to me.

**Comment by EliotAndres** [comment]
@Fabulani Thank you for your fix. I added it to the master branch.
